import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, test } from "bun:test";

import { buildConfigModule, detectPackageManager, resolveApiKey } from "./setup.js";

describe("resolveApiKey", () => {
  const originalAnthropic = process.env.ANTHROPIC_API_KEY;
  let tempHomeDir: string | undefined;

  afterEach(async () => {
    if (originalAnthropic === undefined) {
      delete process.env.ANTHROPIC_API_KEY;
    } else {
      process.env.ANTHROPIC_API_KEY = originalAnthropic;
    }

    if (tempHomeDir) {
      await rm(tempHomeDir, { recursive: true, force: true });
      tempHomeDir = undefined;
    }
  });

  test("returns flag value when provided", () => {
    process.env.ANTHROPIC_API_KEY = "env-value";

    const resolved = resolveApiKey("flag-value", "ANTHROPIC_API_KEY");

    expect(resolved).toBe("flag-value");
  });

  test("returns env var when flag is absent", () => {
    process.env.ANTHROPIC_API_KEY = "env-value";

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY");

    expect(resolved).toBe("env-value");
  });

  test("returns OpenClaw env var when shell env is absent", async () => {
    delete process.env.ANTHROPIC_API_KEY;

    tempHomeDir = await mkdtemp(path.join(os.tmpdir(), "orca-setup-test-"));
    const openclawDir = path.join(tempHomeDir, ".openclaw");
    await mkdir(openclawDir, { recursive: true });
    const configPath = path.join(openclawDir, "openclaw.json");
    await writeFile(
      configPath,
      JSON.stringify({ env: { vars: { ANTHROPIC_API_KEY: "gateway-value" } } }),
      "utf8"
    );

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY", configPath);

    expect(resolved).toBe("gateway-value");
  });

  test("treats OpenClaw 1Password refs as configured", async () => {
    delete process.env.ANTHROPIC_API_KEY;

    tempHomeDir = await mkdtemp(path.join(os.tmpdir(), "orca-setup-test-"));
    const openclawDir = path.join(tempHomeDir, ".openclaw");
    await mkdir(openclawDir, { recursive: true });
    const configPath = path.join(openclawDir, "openclaw.json");
    await writeFile(
      configPath,
      JSON.stringify({ env: { vars: { ANTHROPIC_API_KEY: "op://Eve/Anthropic/credential" } } }),
      "utf8"
    );

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY", configPath);

    expect(resolved).toBe("op://Eve/Anthropic/credential");
  });

  test("returns undefined when no source provides a key", async () => {
    delete process.env.ANTHROPIC_API_KEY;

    tempHomeDir = await mkdtemp(path.join(os.tmpdir(), "orca-setup-test-"));
    const configPath = path.join(tempHomeDir, ".openclaw", "openclaw.json");

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY", configPath);

    expect(resolved).toBeUndefined();
  });
});

describe("detectPackageManager", () => {
  test("prefers brew over other package managers", () => {
    const manager = detectPackageManager((command) => command === "brew" || command === "apt");

    expect(manager).toBe("brew");
  });

  test("returns apt when brew is unavailable", () => {
    const manager = detectPackageManager((command) => command === "apt");

    expect(manager).toBe("apt");
  });

  test("returns winget when only winget is available", () => {
    const manager = detectPackageManager((command) => command === "winget");

    expect(manager).toBe("winget");
  });

  test("returns null when no package manager is found", () => {
    const manager = detectPackageManager(() => false);

    expect(manager).toBeNull();
  });
});

describe("buildConfigModule", () => {
  test("builds module string with both API keys", () => {
    const moduleText = buildConfigModule({
      anthropicApiKey: "sk-ant-test",
      openaiApiKey: "sk-openai-test"
    });

    expect(moduleText).toBe(
      "// generated by orca setup\n" +
        "export default {\n" +
        '  anthropicApiKey: "sk-ant-test",\n' +
        '  openaiApiKey: "sk-openai-test",\n' +
        "};\n"
    );
  });

  test("omits missing keys", () => {
    const moduleText = buildConfigModule({
      anthropicApiKey: "sk-ant-test"
    });

    expect(moduleText).toBe(
      "// generated by orca setup\n" +
        "export default {\n" +
        '  anthropicApiKey: "sk-ant-test",\n' +
        "};\n"
    );
  });
});
