import { execSync, spawnSync } from "node:child_process";
import { constants as fsConstants, readFileSync } from "node:fs";
import { access, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import readline from "node:readline/promises";
import { pathToFileURL } from "node:url";

import chalk from "chalk";
import type { Command } from "commander";

import type { OrcaConfig } from "../../types/index.js";

export interface SetupCommandOptions {
  anthropicKey?: string;
  openaiKey?: string;
  check?: boolean;
  global?: boolean;
  project?: boolean;
}

type PackageManager = "brew" | "apt" | "winget";
type CheckStatus = "pass" | "fail" | "warn";
type ApiKeyConfig = {
  anthropicApiKey?: string;
  openaiApiKey?: string;
};

type CheckResult = {
  name: string;
  status: CheckStatus;
  detail: string;
};

function serializeForModule(value: unknown, depth = 0): string {
  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);

  if (value === null) {
    return "null";
  }

  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }

    const items = value.map((item) => `${childIndent}${serializeForModule(item, depth + 1)}`);
    return `[\n${items.join(",\n")}\n${indent}]`;
  }

  if (typeof value === "function") {
    return value.toString();
  }

  if (typeof value === "object") {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    if (entries.length === 0) {
      return "{}";
    }

    const body = entries.map(([key, item]) => {
      const safeKey = /^[$A-Z_][0-9A-Z_$]*$/i.test(key) ? key : JSON.stringify(key);
      return `${childIndent}${safeKey}: ${serializeForModule(item, depth + 1)}`;
    });
    return `{\n${body.join(",\n")}\n${indent}}`;
  }

  return "undefined";
}

function supportsPrompting(): boolean {
  return Boolean(process.stdin.isTTY);
}

function commandExists(command: string): boolean {
  const result = spawnSync("which", [command], { stdio: "ignore" });
  return result.status === 0;
}

export function resolveApiKey(
  flagValue: string | undefined,
  envVarName: string,
  openclawConfigPath?: string
): string | undefined {
  if (flagValue && flagValue.trim().length > 0) {
    return flagValue.trim();
  }

  const envValue = process.env[envVarName];
  if (envValue && envValue.trim().length > 0) {
    return envValue.trim();
  }

  const openclawValue = readOpenclawEnvVar(envVarName, openclawConfigPath);
  if (openclawValue) {
    return openclawValue;
  }

  return undefined;
}

function readOpenclawEnvVar(envVarName: string, openclawConfigPath?: string): string | undefined {
  const configPath = openclawConfigPath ?? path.join(os.homedir(), ".openclaw", "openclaw.json");
  try {
    const fileText = readFileSync(configPath, "utf8");
    const parsed = JSON.parse(fileText) as { env?: { vars?: Record<string, unknown> } };
    const value = parsed.env?.vars?.[envVarName];

    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }

    if (value && typeof value === "object") {
      const candidateObject = value as {
        value?: unknown;
        ref?: unknown;
        opRef?: unknown;
        reference?: unknown;
      };

      for (const candidate of [
        candidateObject.value,
        candidateObject.ref,
        candidateObject.opRef,
        candidateObject.reference
      ]) {
        if (typeof candidate === "string" && candidate.trim().length > 0) {
          return candidate.trim();
        }
      }
    }
  } catch {
    return undefined;
  }

  return undefined;
}

export function detectPackageManager(
  exists: (command: string) => boolean = commandExists
): PackageManager | null {
  if (exists("brew")) {
    return "brew";
  }

  if (exists("apt")) {
    return "apt";
  }

  if (exists("winget")) {
    return "winget";
  }

  return null;
}

export function buildConfigModule({ anthropicApiKey, openaiApiKey }: ApiKeyConfig): string {
  const lines = ["// generated by orca setup", "export default {"];

  if (anthropicApiKey !== undefined) {
    lines.push(`  anthropicApiKey: ${JSON.stringify(anthropicApiKey)},`);
  }

  if (openaiApiKey !== undefined) {
    lines.push(`  openaiApiKey: ${JSON.stringify(openaiApiKey)},`);
  }

  lines.push("};", "");
  return lines.join("\n");
}

function buildMergedConfigModule(config: OrcaConfig): string {
  return `// generated by orca setup\nexport default ${serializeForModule(config)};\n`;
}

function icon(status: CheckStatus): string {
  if (status === "pass") {
    return chalk.green("✓");
  }

  if (status === "fail") {
    return chalk.red("✗");
  }

  return chalk.yellow("!");
}

function printSummary(results: CheckResult[]): void {
  const width = Math.max(...results.map((result) => result.name.length), 1);

  for (const result of results) {
    console.log(`  ${icon(result.status)} ${result.name.padEnd(width, " ")}  ${result.detail}`);
  }
}

function checkGitOrigin(): { inRepo: boolean; hasOrigin: boolean } {
  const repoCheck = spawnSync("git", ["rev-parse", "--git-dir"], { stdio: "ignore" });
  if (repoCheck.status !== 0) {
    return { inRepo: false, hasOrigin: false };
  }

  const originCheck = spawnSync("git", ["remote", "get-url", "origin"], { stdio: "ignore" });
  return { inRepo: true, hasOrigin: originCheck.status === 0 };
}

async function promptForApiKey(
  rl: readline.Interface,
  currentValue: string | undefined,
  promptText: string
): Promise<string | undefined> {
  if (currentValue || !supportsPrompting()) {
    return currentValue;
  }

  const value = (await rl.question(promptText)).trim();
  return value.length > 0 ? value : undefined;
}

function runGhAuthStatus(): { authenticated: boolean; detail: string } {
  const result = spawnSync("gh", ["auth", "status"], { encoding: "utf8" });
  if (result.status === 0) {
    const version = execSync("gh --version", { encoding: "utf8" }).split("\n")[0]?.trim();
    return {
      authenticated: true,
      detail: version ? `${version} (authenticated)` : "installed (authenticated)"
    };
  }

  return {
    authenticated: false,
    detail: "installed (not authenticated)"
  };
}

function installGhVia(packageManager: PackageManager): void {
  if (packageManager === "brew") {
    spawnSync("brew", ["install", "gh"], { stdio: "inherit" });
    return;
  }

  if (packageManager === "apt") {
    spawnSync("sudo", ["apt", "install", "gh"], { stdio: "inherit" });
    return;
  }

  spawnSync("winget", ["install", "GitHub.cli"], { stdio: "inherit" });
}

async function loadExistingConfig(configPath: string): Promise<OrcaConfig | undefined> {
  try {
    await access(configPath, fsConstants.R_OK);
  } catch {
    return undefined;
  }

  const importUrl = `${pathToFileURL(configPath).href}?t=${Date.now()}`;
  const imported = await import(importUrl);
  const candidate = "default" in imported ? imported.default : imported;

  if (candidate && typeof candidate === "object") {
    return candidate as OrcaConfig;
  }

  return undefined;
}

async function saveConfig(
  configPath: string,
  keys: ApiKeyConfig
): Promise<void> {
  const existing = await loadExistingConfig(configPath);
  const merged: OrcaConfig = {
    ...existing,
    ...(keys.anthropicApiKey !== undefined ? { anthropicApiKey: keys.anthropicApiKey } : {}),
    ...(keys.openaiApiKey !== undefined ? { openaiApiKey: keys.openaiApiKey } : {})
  };

  const moduleText = buildConfigModule({
    ...(merged.anthropicApiKey !== undefined ? { anthropicApiKey: merged.anthropicApiKey } : {}),
    ...(merged.openaiApiKey !== undefined ? { openaiApiKey: merged.openaiApiKey } : {})
  });
  const fullModuleText = buildMergedConfigModule(merged);

  await mkdir(path.dirname(configPath), { recursive: true });
  await writeFile(
    configPath,
    existing ? fullModuleText : moduleText,
    "utf8"
  );
}

function parseSaveTarget(options: SetupCommandOptions): "global" | "project" | null {
  if (options.global && options.project) {
    throw new Error("--global and --project cannot be used together");
  }

  if (options.project) {
    return "project";
  }

  if (options.global) {
    return "global";
  }

  return null;
}

async function chooseSaveTarget(
  rl: readline.Interface,
  explicitTarget: "global" | "project" | null
): Promise<"global" | "project" | "skip"> {
  if (explicitTarget) {
    return explicitTarget;
  }

  if (!supportsPrompting()) {
    return "global";
  }

  const answer = (
    await rl.question("Save API keys to config? [G]lobal (~/.orca/config.js) / [P]roject (./orca.config.js) / [S]kip: ")
  )
    .trim()
    .toLowerCase();

  if (answer === "p" || answer === "project") {
    return "project";
  }

  if (answer === "s" || answer === "skip") {
    return "skip";
  }

  return "global";
}

function getConfigPath(target: "global" | "project"): string {
  if (target === "project") {
    return path.resolve("orca.config.js");
  }

  return path.join(os.homedir(), ".orca", "config.js");
}

export async function setupCommandHandler(options: SetupCommandOptions): Promise<void> {
  const explicitTarget = parseSaveTarget(options);
  const checkMode = Boolean(options.check);
  const canPrompt = supportsPrompting() && !checkMode;
  const rl = canPrompt
    ? readline.createInterface({
        input: process.stdin,
        output: process.stdout
      })
    : null;

  const results: CheckResult[] = [];
  let anthropicApiKey = resolveApiKey(options.anthropicKey, "ANTHROPIC_API_KEY");
  let openaiApiKey = resolveApiKey(options.openaiKey, "OPENAI_API_KEY");

  try {
    if (!checkMode && rl) {
      anthropicApiKey = await promptForApiKey(rl, anthropicApiKey, "Enter your Anthropic API key (sk-ant-...): ");
    }

    if (anthropicApiKey) {
      results.push({ name: "ANTHROPIC_API_KEY", status: "pass", detail: checkMode ? "set" : "found" });
      if (!checkMode) console.log(chalk.green("✓ Anthropic API key found"));
    } else {
      results.push({ name: "ANTHROPIC_API_KEY", status: "warn", detail: "not set" });
      if (!checkMode) console.log(chalk.yellow("! ANTHROPIC_API_KEY not set"));
    }

    if (!checkMode && rl) {
      openaiApiKey = await promptForApiKey(rl, openaiApiKey, "Enter your OpenAI API key (sk-...): ");
    }

    if (openaiApiKey) {
      results.push({ name: "OPENAI_API_KEY", status: "pass", detail: checkMode ? "set" : "found" });
      if (!checkMode) console.log(chalk.green("✓ OpenAI API key found"));
    } else {
      results.push({ name: "OPENAI_API_KEY", status: "warn", detail: "not set" });
      if (!checkMode) console.log(chalk.yellow("! OPENAI_API_KEY not set"));
    }

    const ghAvailable = commandExists("gh");
    if (!ghAvailable) {
      results.push({ name: "gh CLI", status: "warn", detail: "not found" });
      if (!checkMode) {
        console.log(chalk.yellow("! gh CLI not found — needed for orca pr commands"));
      }

      if (!checkMode && rl) {
        const installAnswer = (await rl.question("Install gh CLI? (y/N): ")).trim().toLowerCase();
        if (installAnswer === "y" || installAnswer === "yes") {
          const packageManager = detectPackageManager();
          if (packageManager) {
            installGhVia(packageManager);
          } else {
            console.log("Install manually: https://cli.github.com");
          }
        } else {
          console.log("Skipping gh CLI installation.");
        }
      } else if (!checkMode) {
        console.log("Skipping gh CLI installation (non-interactive mode).");
      }
    } else {
      const auth = runGhAuthStatus();
      if (auth.authenticated) {
        results.push({ name: "gh CLI", status: "pass", detail: auth.detail });
      } else {
        results.push({ name: "gh CLI", status: "warn", detail: auth.detail });
      }

      if (!checkMode && !auth.authenticated) {
        console.log(chalk.yellow("! gh CLI is not authenticated"));
        if (rl) {
          const loginAnswer = (await rl.question("Run gh auth login now? (y/N): ")).trim().toLowerCase();
          if (loginAnswer === "y" || loginAnswer === "yes") {
            spawnSync("gh", ["auth", "login"], { stdio: "inherit" });
          }
        }
      }
    }

    const gitCheck = checkGitOrigin();
    if (!gitCheck.inRepo) {
      results.push({ name: "git origin", status: "warn", detail: "not in a git repo" });
      if (!checkMode) {
        console.log(chalk.yellow("! Not in a git repo — orca pr commands require one"));
      }
    } else if (!gitCheck.hasOrigin) {
      results.push({ name: "git origin", status: "warn", detail: "not set" });
      if (!checkMode) {
        console.log(chalk.yellow('! No git remote "origin" set'));
      }
    } else {
      results.push({ name: "git origin", status: "pass", detail: "found" });
      if (!checkMode) {
        console.log(chalk.green("✓ Git remote origin found"));
      }
    }

    if (!checkMode && (anthropicApiKey || openaiApiKey)) {
      const target = rl ? await chooseSaveTarget(rl, explicitTarget) : explicitTarget ?? "global";
      if (target !== "skip") {
        const configPath = getConfigPath(target);
        await saveConfig(configPath, {
          ...(anthropicApiKey !== undefined ? { anthropicApiKey } : {}),
          ...(openaiApiKey !== undefined ? { openaiApiKey } : {})
        });

        const printedPath = target === "global" ? "~/.orca/config.js" : "./orca.config.js";
        console.log(chalk.green(`✓ Config saved to ${printedPath}`));
      }
    }

    if (!checkMode) {
      console.log("\nSummary:");
    }
    printSummary(results);

    if (checkMode) {
      const requiredPass = Boolean(anthropicApiKey) && Boolean(openaiApiKey);
      if (!requiredPass) {
        console.log(
          chalk.dim("\nSome API keys aren't configured yet. Run `orca setup` to add them interactively,")
        );
        console.log(
          chalk.dim("or pass them directly: orca setup --anthropic-key <key> --openai-key <key>")
        );
      }
      process.exitCode = requiredPass ? 0 : 1;
      return;
    }

    if (!anthropicApiKey || !openaiApiKey) {
      process.exitCode = 1;
    }
  } finally {
    rl?.close();
  }
}

export function registerSetupCommand(program: Command): void {
  program
    .command("setup")
    .description("Run first-time setup and environment checks")
    .option("--anthropic-key <key>", "Provide ANTHROPIC_API_KEY directly")
    .option("--openai-key <key>", "Provide OPENAI_API_KEY directly")
    .option("--check", "Run non-interactive validation checks")
    .option("--global", "Save config to ~/.orca/config.js")
    .option("--project", "Save config to ./orca.config.js")
    .action(async (commandOptions: SetupCommandOptions) => {
      await setupCommandHandler(commandOptions);
    });
}
