import { afterEach, describe, expect, test } from "bun:test";

import { buildConfigModule, detectPackageManager, resolveApiKey } from "./setup.js";

describe("resolveApiKey", () => {
  const originalAnthropic = process.env.ANTHROPIC_API_KEY;

  afterEach(() => {
    if (originalAnthropic === undefined) {
      delete process.env.ANTHROPIC_API_KEY;
    } else {
      process.env.ANTHROPIC_API_KEY = originalAnthropic;
    }
  });

  test("returns flag value when provided", () => {
    process.env.ANTHROPIC_API_KEY = "env-value";

    const resolved = resolveApiKey("flag-value", "ANTHROPIC_API_KEY");

    expect(resolved).toBe("flag-value");
  });

  test("returns env var when flag is absent", () => {
    process.env.ANTHROPIC_API_KEY = "env-value";

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY");

    expect(resolved).toBe("env-value");
  });

  test("returns undefined when both are absent", () => {
    delete process.env.ANTHROPIC_API_KEY;

    const resolved = resolveApiKey(undefined, "ANTHROPIC_API_KEY");

    expect(resolved).toBeUndefined();
  });
});

describe("detectPackageManager", () => {
  test("prefers brew over other package managers", () => {
    const manager = detectPackageManager((command) => command === "brew" || command === "apt");

    expect(manager).toBe("brew");
  });

  test("returns apt when brew is unavailable", () => {
    const manager = detectPackageManager((command) => command === "apt");

    expect(manager).toBe("apt");
  });

  test("returns winget when only winget is available", () => {
    const manager = detectPackageManager((command) => command === "winget");

    expect(manager).toBe("winget");
  });

  test("returns null when no package manager is found", () => {
    const manager = detectPackageManager(() => false);

    expect(manager).toBeNull();
  });
});

describe("buildConfigModule", () => {
  test("builds module string with both API keys", () => {
    const moduleText = buildConfigModule({
      anthropicApiKey: "sk-ant-test",
      openaiApiKey: "sk-openai-test"
    });

    expect(moduleText).toBe(
      "// generated by orca setup\n" +
        "export default {\n" +
        '  anthropicApiKey: "sk-ant-test",\n' +
        '  openaiApiKey: "sk-openai-test",\n' +
        "};\n"
    );
  });

  test("omits missing keys", () => {
    const moduleText = buildConfigModule({
      anthropicApiKey: "sk-ant-test"
    });

    expect(moduleText).toBe(
      "// generated by orca setup\n" +
        "export default {\n" +
        '  anthropicApiKey: "sk-ant-test",\n' +
        "};\n"
    );
  });
});
