import { execSync, spawnSync } from "node:child_process";
import { constants as fsConstants, readFileSync } from "node:fs";
import { access, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import readline from "node:readline/promises";
import { pathToFileURL } from "node:url";

import chalk from "chalk";
import { InvalidArgumentError, type Command } from "commander";

import type { OrcaConfig } from "../../types/index.js";

export interface SetupCommandOptions {
  openaiKey?: string;
  global?: boolean;
  project?: boolean;
  ts?: boolean;
  executor?: "codex";
  projectConfigTemplate?: boolean;
  skipProjectConfig?: boolean;
}

type PackageManager = "brew" | "apt" | "winget";
type CheckStatus = "pass" | "fail" | "warn";
type ApiKeyConfig = { openaiApiKey?: string; executor?: "codex" };
type CheckResult = { name: string; status: CheckStatus; detail: string };

type ResolveApiKeyOptions = { openclawConfigPath?: string; homedir?: string };

export function resolveApiKey(
  flagValue: string | undefined,
  envVarName: string,
  openclawConfigPathOrOptions?: string | ResolveApiKeyOptions,
  maybeOptions?: ResolveApiKeyOptions,
): string | undefined {
  if (flagValue && flagValue.trim().length > 0) return flagValue.trim();
  if (envVarName === "OPENAI_API_KEY") {
    const orca = process.env.ORCA_OPENAI_API_KEY;
    if (orca?.trim()) return orca.trim();
  }
  const envValue = process.env[envVarName];
  if (envValue?.trim()) return envValue.trim();

  const options =
    typeof openclawConfigPathOrOptions === "string"
      ? { ...maybeOptions, openclawConfigPath: openclawConfigPathOrOptions }
      : (openclawConfigPathOrOptions ?? {});
  const homedir = options.homedir ?? os.homedir();
  const configPath = options.openclawConfigPath ?? path.join(homedir, ".openclaw", "openclaw.json");
  try {
    const parsed = JSON.parse(readFileSync(configPath, "utf8")) as { env?: { vars?: Record<string, unknown> } };
    const value = parsed.env?.vars?.[envVarName];
    if (typeof value === "string" && value.trim().length > 0) return value.trim();
  } catch {
    return undefined;
  }
  return undefined;
}

export function readCodexAuthJson(homedir: string = os.homedir()): string | undefined {
  const authPath = path.join(homedir, ".codex", "auth.json");
  try {
    const parsed = JSON.parse(readFileSync(authPath, "utf8")) as {
      OPENAI_API_KEY?: unknown;
      tokens?: { access_token?: unknown };
    };
    if (typeof parsed.tokens?.access_token === "string" && parsed.tokens.access_token.trim())
      return parsed.tokens.access_token.trim();
    if (typeof parsed.OPENAI_API_KEY === "string" && parsed.OPENAI_API_KEY.trim()) return parsed.OPENAI_API_KEY.trim();
  } catch {
    return undefined;
  }
  return undefined;
}

export function readClaudeCodeKeychain(): string | undefined {
  return undefined;
}

function parseExecutorOption(value: string): "codex" {
  if (value === "codex") return value;
  throw new InvalidArgumentError("executor must be: codex");
}

export function buildConfigModule({ openaiApiKey, executor }: ApiKeyConfig): string {
  const lines = ["// generated by orca setup", "export default {"];
  if (openaiApiKey !== undefined) lines.push(`  openaiApiKey: ${JSON.stringify(openaiApiKey)},`);
  if (executor !== undefined) lines.push(`  executor: ${JSON.stringify(executor)},`);
  lines.push("};", "");
  return lines.join("\n");
}

function serializeForModule(value: unknown, depth = 0): string {
  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[\n${value.map((item) => `${childIndent}${serializeForModule(item, depth + 1)}`).join(",\n")}\n${indent}]`;
  }
  if (typeof value === "function") return value.toString();
  if (typeof value === "object") {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    if (entries.length === 0) return "{}";
    return `{\n${entries.map(([key, item]) => `${childIndent}${key}: ${serializeForModule(item, depth + 1)}`).join(",\n")}\n${indent}}`;
  }
  return "undefined";
}

function buildMergedConfigModule(config: OrcaConfig, useTs: boolean): string {
  if (useTs) {
    return [
      "// generated by orca setup",
      'import type { OrcaConfig } from "orcastrator";',
      "",
      `export default ${serializeForModule(config)} satisfies OrcaConfig;`,
      "",
    ].join("\n");
  }
  return `// generated by orca setup\nexport default ${serializeForModule(config)};\n`;
}

function supportsPrompting(): boolean {
  return Boolean(process.stdin.isTTY);
}
function commandExists(command: string): boolean {
  return spawnSync("which", [command], { stdio: "ignore" }).status === 0;
}
function detectPackageManager(): PackageManager | null {
  if (commandExists("brew")) return "brew";
  if (commandExists("apt")) return "apt";
  if (commandExists("winget")) return "winget";
  return null;
}
function installGhVia(packageManager: PackageManager): void {
  if (packageManager === "brew") spawnSync("brew", ["install", "gh"], { stdio: "inherit" });
  else if (packageManager === "apt") spawnSync("sudo", ["apt", "install", "gh"], { stdio: "inherit" });
  else spawnSync("winget", ["install", "GitHub.cli"], { stdio: "inherit" });
}
function runGhAuthStatus(): { authenticated: boolean; detail: string } {
  const result = spawnSync("gh", ["auth", "status"], { encoding: "utf8" });
  if (result.status === 0) {
    const version = execSync("gh --version", { encoding: "utf8" }).split("\n")[0]?.trim();
    return { authenticated: true, detail: version ? `${version} (authenticated)` : "installed (authenticated)" };
  }
  return { authenticated: false, detail: "installed (not authenticated)" };
}
function icon(status: CheckStatus): string {
  if (status === "pass") return chalk.green("✓");
  if (status === "fail") return chalk.red("✗");
  return chalk.yellow("!");
}
function printSummary(results: CheckResult[]): void {
  const width = Math.max(...results.map((result) => result.name.length), 1);
  for (const result of results)
    console.log(`  ${icon(result.status)} ${result.name.padEnd(width, " ")}  ${result.detail}`);
}

function parseSaveTarget(options: SetupCommandOptions): "global" | "project" | null {
  if (options.global && options.project) throw new Error("--global and --project cannot be used together");
  if (options.project) return "project";
  if (options.global) return "global";
  return null;
}

function getConfigPath(target: "global" | "project", useTs: boolean): string {
  return target === "project"
    ? path.resolve(useTs ? "orca.config.ts" : "orca.config.js")
    : path.join(os.homedir(), ".orca", useTs ? "config.ts" : "config.js");
}

async function loadExistingConfig(configPath: string): Promise<OrcaConfig | undefined> {
  try {
    await access(configPath, fsConstants.R_OK);
  } catch {
    return undefined;
  }
  const imported = await import(`${pathToFileURL(configPath).href}?t=${Date.now()}`);
  const candidate = "default" in imported ? imported.default : imported;
  return candidate && typeof candidate === "object" ? (candidate as OrcaConfig) : undefined;
}

async function saveConfig(
  configPath: string,
  keys: ApiKeyConfig,
  executor: "codex" | undefined,
  useTs: boolean,
): Promise<void> {
  const existing = await loadExistingConfig(configPath);
  const merged: OrcaConfig = {
    ...existing,
    ...(keys.openaiApiKey ? { openaiApiKey: keys.openaiApiKey } : {}),
    ...(executor ? { executor } : {}),
  };
  await mkdir(path.dirname(configPath), { recursive: true });
  await writeFile(
    configPath,
    existing
      ? buildMergedConfigModule(merged, useTs)
      : buildConfigModule({
          ...(merged.openaiApiKey ? { openaiApiKey: merged.openaiApiKey } : {}),
          ...(merged.executor ? { executor: "codex" } : {}),
        }),
    "utf8",
  );
}

export async function setupCommandHandler(options: SetupCommandOptions): Promise<void> {
  const target = parseSaveTarget(options) ?? "global";
  const rl = supportsPrompting() ? readline.createInterface({ input: process.stdin, output: process.stdout }) : null;
  const results: CheckResult[] = [];
  let openaiApiKey = resolveApiKey(options.openaiKey, "OPENAI_API_KEY");
  let persistOpenAi = options.openaiKey !== undefined;

  try {
    let codexAvailable = Boolean(openaiApiKey) || Boolean(readCodexAuthJson());
    if (!codexAvailable && rl) {
      const before = openaiApiKey;
      const value = (await rl.question("Enter your OpenAI API key (sk-...) [optional]: ")).trim();
      openaiApiKey = value || before;
      if (!persistOpenAi && !before && openaiApiKey) persistOpenAi = true;
      codexAvailable = Boolean(openaiApiKey) || Boolean(readCodexAuthJson());
    }

    results.push({
      name: "Codex",
      status: codexAvailable ? "pass" : "warn",
      detail: codexAvailable ? "available" : "not available",
    });

    const ghAvailable = commandExists("gh");
    if (!ghAvailable) {
      results.push({ name: "gh CLI", status: "warn", detail: "not found" });
      if (rl) {
        const installAnswer = (await rl.question("Install gh CLI? (y/N): ")).trim().toLowerCase();
        if (installAnswer === "y" || installAnswer === "yes") {
          const packageManager = detectPackageManager();
          if (packageManager) installGhVia(packageManager);
          else console.log("Install manually: https://cli.github.com");
        }
      }
    } else {
      const auth = runGhAuthStatus();
      results.push({ name: "gh CLI", status: auth.authenticated ? "pass" : "warn", detail: auth.detail });
    }

    const configPath = getConfigPath(target, Boolean(options.ts));
    const resolvedExecutor = options.executor ?? (codexAvailable ? "codex" : undefined);
    await saveConfig(
      configPath,
      persistOpenAi && openaiApiKey ? { openaiApiKey } : {},
      resolvedExecutor,
      Boolean(options.ts),
    );

    const printedPath =
      target === "global"
        ? options.ts
          ? "~/.orca/config.ts"
          : "~/.orca/config.js"
        : options.ts
          ? "./orca.config.ts"
          : "./orca.config.js";
    if (resolvedExecutor) {
      console.log(chalk.green(`✓ Config saved to ${printedPath} (executor: ${resolvedExecutor})`));
      process.exitCode = 0;
    } else {
      console.log(chalk.green(`✓ Config saved to ${printedPath}`));
      console.log("! Codex not detected. Set OPENAI_API_KEY (or ORCA_OPENAI_API_KEY), then run `orca setup` again.");
      process.exitCode = 1;
    }

    console.log("\nSummary:");
    printSummary(results);
  } finally {
    rl?.close();
  }
}

export function registerSetupCommand(program: Command): void {
  program
    .command("setup")
    .description("Run first-time setup and environment checks")
    .option("--openai-key <key>", "Provide OpenAI API key directly")
    .option("--global", "Save config to ~/.orca/config.js (or ~/.orca/config.ts with --ts)")
    .option("--project", "Save config to ./orca.config.js (or ./orca.config.ts with --ts)")
    .option("--ts", "Write TypeScript config (.ts) with OrcaConfig satisfies syntax")
    .option("--executor <value>", "Set executor in written config (codex)", parseExecutorOption)
    .action(async (commandOptions: SetupCommandOptions) => {
      await setupCommandHandler(commandOptions);
    });
}
